### PR TITLE
pr for microverse tse approval: milestone 1 basic project structure

### PR DESCRIPTION
**Pull request by firmoholanda**
in this pr, i implemented the folowing:
- created new app with: create-react-app;
- deleted unnecessary files;
- added big.js using nmp to project;
- tested run app with npm start;
- deployed to heriku on the folowing link: https://calculator-react-firmoholanda.herokuapp.com/

### CODE REVIEW

**Review by shshamim63 — CHANGES_REQUESTED** [review]
## :recycle: Required Changes :recycle: 
___
Hi @firmoholanda :wave: ,
Great job, you have added your own type of footer :clap: . But there are some issues that are blocking me to approve this milestone now. Let's check them.
___
### :spades: Mandatory Changes :spades: 
___
- Please add [`prop-types`](https://www.npmjs.com/package/prop-types) package.json for [typechecking props](https://reactjs.org/docs/typechecking-with-proptypes.html) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/section/propTypes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))
- I cannot see the linter configuration. Please add it by following the instructions in [here](https://github.com/microverseinc/linters-config/tree/master/react-redux)
___
#### Please resolve the above issues and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Comment by firmoholanda** [comment]
in this second pr, i implemented the folowing:

- added prop-types package.json;
- added the linter configuration;
- added .eslintignore
- removed serviceWorker.js
- removed remove .env from github

**Review by shshamim63 — CHANGES_REQUESTED** [review]
## :recycle: Changes Required :recycle: 
___
HI @firmoholanda :wave: 
Nice work :clap: Your project looks almost clean, just need to clean a bit more. Let's do them.
___
### :spades: Mandatory Changes :spades: 
___
- Our Linter is going to run the .eslintrc.json file. So the .eslintrc.js is redundant in here.
- I think this project does not ask you to add tests, so please delete the test directory. If you delete it then .eslintingore can be deleted without any doubt.
___
:rocket: 
While I tried to start the app faced an error related to webpack version problem. If you are facing the same error, there is a simple way to fix it.
- Remove webpack from package.json 'dependencies' section.
- Delete the node_module that is created in your project directory.
- Install the dependencies 'npm install'
It will resolve the issue.
___
#### Please resolve the issues mentioned above and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Comment by firmoholanda** [comment]
in this pr, i implemented the folowing:
- removed eslintrc.js
- removed test dir
- removed .eslintingore
- removed webpack from package.json 'dependencies' section

**Review by Torres-ssf — APPROVED** [review]
### Milestone Approved :+1: 
Hi there @firmoholanda :hand: 
The webpack problem was solved, we are ready to move on :smile: 
Nice going :clap: 

Happy coding :computer: 
**Sérgio Torres**

**Pull request merged**
